apiVersion: v1
kind: Pod
metadata:
  name: broken-pod
  labels:
    app: broken
    purpose: troubleshooting-exercise
spec:
  containers:
  - name: app
    # This image doesn't exist - students will troubleshoot this
    image: nginx:nonexistent-tag-999
    ports:
    - containerPort: 80
