apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv
  labels:
    type: local
    storage-tier: standard
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce  # Can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # Keep data after claim is deleted
  storageClassName: manual
  hostPath:
    path: /mnt/data  # Directory on the node
    type: DirectoryOrCreate
